cities = {
    "Anderson Packers": "AND",
    "Atlanta Hawks": "ATL",
    "Baltimore Bullets": "BLB",
    "Boston Celtics": "BOS",
    "Buffalo Braves": "BUF",
    "Charlotte Bobcats": "CHA",
    "Charlotte Hornets": "CHH",
    "Chicago Bulls": "CHI",
    "Chicago Packers": "CHP",
    "Chicago Stags": "CHS",
    "Chicago Zephyrs": "CHZ",
    "Cincinnati Royals": "CIN",
    "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL",
    "Denver Nuggets": "DEN",
    "Detroit Pistons": "DET",
    "Fort Wayne Pistons": "FTW",
    "Golden State Warriors": "GSW",
    "Houston Rockets": "HOU",
    "Indiana Pacers": "IND",
    "Indianapolis Olympians": "INO",
    "Kansas City Kings": "KCK",
    "Kansas City-Omaha Kings": "KCO",
    "Los Angeles Clippers": "LAC",
    "Los Angeles Lakers": "LAL",
    "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA",
    "Milwaukee Bucks": "MIL",
    "Milwaukee Hawks": "MLH",
    "Minneapolis Lakers": "MNL",
    "Minnesota Timberwolves": "MIN",
    "New Orleans Jazz": "NOJ",
    "New Orleans Hornets": "NOH",
    "New Orleans Pelicans": "NOP",
    "New Orleans/Oklahoma City Hornets": "NOK",
    "New Jersey Nets": "NJN",
    "New York Knicks": "NYK",
    "New York Nets": "NYN",
    "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL",
    "Philadelphia 76ers": "PHI",
    "Philadelphia Warriors": "PHW",
    "Phoenix Suns": "PHO",
    "Portland Trail Blazers": "POR",
    "Rochester Royals": "ROC",
    "Sacramento Kings": "SAC",
    "San Antonio Spurs": "SAS",
    "San Diego Clippers": "SDC",
    "San Diego Rockets": "SDR",
    "San Francisco Warriors": "SFW",
    "Seattle SuperSonics": "SEA",
    "Sheboygan Red Skins": "SHE",
    "St. Louis Bombers": "STB",
    "St. Louis Hawks": "STL",
    "Syracuse Nationals": "SYR",
    "Toronto Raptors": "TOR",
    "Tri-Cities Blackhawks": "TRI",
    "Utah Jazz": "UTA",
    "Washington Bullets": "WSB",
    "Washington Capitols": "WSC",
    "Washington Wizards": "WAS",
    "Waterloo Hawks": "WAT",
    "Vancouver Grizzlies": "VAN",
}
